version: '3'
services:
  aeya-acceptor:
    build:
      .
    image:
      aeya-acceptor
    ports:
      - 1515:1515
    volumes:
      - /srv/hdd4t/filebrowser/filehosting:/app/filehosting
    restart: 'unless-stopped'