version: '3'
services:
  aeya-acceptor:
    build:
      .
    ports:
      - 1515:1515
    volumes:
      - /srv/hdd4t/filebrowser/filehosting:/app/filehosting
    restart: 'unless-stopped'
    environment:
      - DB_USER=your_username
      - DB_PASSWORD=your_password
      - DB_HOST=localhost